<?php

namespace Database\Seeders;

use App\Models\business\Place;
use App\Models\business\Product;
use App\Models\business\State;
use App\Models\business\Unit;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChecklistSeeder extends Seeder
{
    /**
     * Checklist de mercado real (agosto 2026): mezcla items ya comprados con
     * precios y lugares reales e items todavía pendientes, para que el checkout,
     * la despensa y los rankings del dashboard tengan datos con los que trabajar.
     */
    public function run(): void
    {
        $user = User::where('email', 'jhonatanguerrero@outlook.com')->first();
        $state = State::where('type', 'CHECKLIST')->where('name', 'Abierta')->first();

        if (! $user || ! $state) {
            return;
        }

        $products = Product::pluck('id', 'name');
        $units = Unit::pluck('id', 'name');
        $places = Place::pluck('id', 'name');

        $checklistId = DB::table('checklists')->insertGetId([
            'user_id' => $user->id,
            'name' => 'Mercado de agosto',
            'state_id' => $state->id,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $items = [
            [
                'product' => 'Arroz',
                'quantity_planned' => 3,
                'unit_planned' => 'Kilogramo',
                'quantity_at_home' => 3,
                'unit_at_home' => 'Kilogramo',
                'was_bought' => true,
                'quantity_bought' => 5,
                'unit_bought' => 'Kilogramo',
                'place' => 'Alkosto',
                'unit_price' => 3180,
                'total_price' => 15900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Atun',
                'quantity_planned' => 2,
                'unit_planned' => 'Lata',
                'quantity_at_home' => 2,
                'unit_at_home' => 'Lata',
                'was_bought' => true,
                'quantity_bought' => 2,
                'unit_bought' => 'Lata',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 4450,
                'total_price' => 8900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Bechamel',
                'quantity_planned' => 2,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 2,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 2850,
                'total_price' => 5700,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Boloñesa',
                'quantity_planned' => 2,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 2,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 2850,
                'total_price' => 5700,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Cafe',
                'quantity_planned' => 2,
                'unit_planned' => 'Libra',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 2,
                'unit_bought' => 'Libra',
                'place' => 'Alkosto',
                'unit_price' => 20965,
                'total_price' => 41930,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Chorizo',
                'quantity_planned' => 2,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => 1,
                'unit_at_home' => 'Unidad',
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 8100,
                'total_price' => 8100,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Café Instantáneo',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 79900,
                'total_price' => 79900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Aromáticas',
                'quantity_planned' => 1,
                'unit_planned' => 'Caja',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Caja',
                'place' => 'Alkosto',
                'unit_price' => 5900,
                'total_price' => 5900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Ducales',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 9200,
                'total_price' => 9200,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Galletas saltinas',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 6900,
                'total_price' => 6900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Gomas orion',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 9600,
                'total_price' => 9600,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Guantes',
                'quantity_planned' => 2,
                'unit_planned' => 'Par',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 2,
                'unit_bought' => 'Par',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 7300,
                'total_price' => 14600,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Huevos',
                'quantity_planned' => 1,
                'unit_planned' => 'Caja',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Inhalador',
                'quantity_planned' => 2,
                'unit_planned' => 'Unidad',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 2,
                'unit_bought' => 'Unidad',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 17900,
                'total_price' => 35800,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Jabón Rey',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => 1,
                'unit_at_home' => 'Unidad',
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 9900,
                'total_price' => 9900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Lasagna',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 2,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 4887.5,
                'total_price' => 9775,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Leche',
                'quantity_planned' => 2,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 2,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 28300,
                'total_price' => 56600,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Lentejas',
                'quantity_planned' => 1,
                'unit_planned' => 'Kilogramo',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Kilogramo',
                'place' => 'Alkosto',
                'unit_price' => 4500,
                'total_price' => 4500,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Mantequilla',
                'quantity_planned' => 1,
                'unit_planned' => 'Unidad',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Jamón',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 12950,
                'total_price' => 12950,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Jamón Serrano Tajado',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Azucar',
                'quantity_planned' => 1,
                'unit_planned' => 'Libra',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Libra',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 3900,
                'total_price' => 3900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Morcilla',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 11100,
                'total_price' => 11100,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Pan hamburguesa',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 3900,
                'total_price' => 3900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Carne Hamburguesa',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 6720,
                'total_price' => 6720,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Pan Sándwich',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 5300,
                'total_price' => 5300,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Panela',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 6600,
                'total_price' => 6600,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Ramen',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 11300,
                'total_price' => 11300,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Salchichas',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 7800,
                'total_price' => 7800,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Sardinas',
                'quantity_planned' => 1,
                'unit_planned' => 'Lata',
                'quantity_at_home' => 2,
                'unit_at_home' => 'Lata',
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Tallarines',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Toallas higiénicas',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 14400,
                'total_price' => 14400,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Tostadas',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 5500,
                'total_price' => 5500,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Yogurt',
                'quantity_planned' => 1,
                'unit_planned' => 'Litro',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 2,
                'unit_bought' => 'Litro',
                'place' => 'Alkosto',
                'unit_price' => 12450,
                'total_price' => 24900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Tocineta',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Ajo en Polvo',
                'quantity_planned' => 2,
                'unit_planned' => 'Bolsa',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Crema de leche',
                'quantity_planned' => 4,
                'unit_planned' => 'Bolsa',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Galletas Festival',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 16900,
                'total_price' => 16900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Detergente Líquido',
                'quantity_planned' => 1,
                'unit_planned' => 'Galón',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Galón',
                'place' => 'Alkosto',
                'unit_price' => 43900,
                'total_price' => 43900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Limpiatodo',
                'quantity_planned' => 1,
                'unit_planned' => 'Litro',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Maíz Congelado',
                'quantity_planned' => 1,
                'unit_planned' => 'Bolsa',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Papas a la francesa',
                'quantity_planned' => 1,
                'unit_planned' => 'Bolsa',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Pastillas baño',
                'quantity_planned' => 2,
                'unit_planned' => 'Unidad',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Pimienta Molida',
                'quantity_planned' => 2,
                'unit_planned' => 'Bolsa',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Toallas Desinfectante',
                'quantity_planned' => 1,
                'unit_planned' => 'Bolsa',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Toallas humedas',
                'quantity_planned' => 1,
                'unit_planned' => 'Bolsa',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Toallas mascotas',
                'quantity_planned' => 1,
                'unit_planned' => 'Bolsa',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Mogolla',
                'quantity_planned' => 1,
                'unit_planned' => 'Bolsa',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Chocolate En Polvo',
                'quantity_planned' => 1,
                'unit_planned' => 'Bolsa',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Bolsa',
                'place' => 'Alkosto',
                'unit_price' => 16200,
                'total_price' => 16200,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Protectores',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 18500,
                'total_price' => 18500,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Jabón corporal',
                'quantity_planned' => 2,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 2,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 15200,
                'total_price' => 30400,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Guantes Negros',
                'quantity_planned' => 1,
                'unit_planned' => 'Par',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Par',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 5500,
                'total_price' => 5500,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Cerveza six',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 12800,
                'total_price' => 12800,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Arroz con leche',
                'quantity_planned' => 1,
                'unit_planned' => 'Unidad',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Unidad',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 5400,
                'total_price' => 5400,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Arepa con queso',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 4950,
                'total_price' => 4950,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Margarina',
                'quantity_planned' => 1,
                'unit_planned' => 'Unidad',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Unidad',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 4700,
                'total_price' => 4700,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Sándwich',
                'quantity_planned' => 1,
                'unit_planned' => 'Unidad',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Unidad',
                'place' => 'Mercado Zapatoca',
                'unit_price' => 5900,
                'total_price' => 5900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Leche Achocolatada',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 8900,
                'total_price' => 8900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Avena',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => false,
                'quantity_bought' => null,
                'unit_bought' => null,
                'place' => null,
                'unit_price' => null,
                'total_price' => null,
                'purchase_date' => null,
            ],
            [
                'product' => 'Avena Bolsa',
                'quantity_planned' => 1,
                'unit_planned' => 'Paquete',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 1,
                'unit_bought' => 'Paquete',
                'place' => 'Alkosto',
                'unit_price' => 8900,
                'total_price' => 8900,
                'purchase_date' => '2026-08-05',
            ],
            [
                'product' => 'Arveja con cáscara',
                'quantity_planned' => 600,
                'unit_planned' => 'Gramo',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 600,
                'unit_bought' => 'Gramo',
                'place' => 'Don Camilo',
                'unit_price' => 4.96,
                'total_price' => 2975,
                'purchase_date' => '2026-08-12',
            ],
            [
                'product' => 'Papa Pastusa (Bolsa)',
                'quantity_planned' => 5,
                'unit_planned' => 'Libra',
                'quantity_at_home' => null,
                'unit_at_home' => null,
                'was_bought' => true,
                'quantity_bought' => 5,
                'unit_bought' => 'Libra',
                'place' => 'Don Camilo',
                'unit_price' => 840,
                'total_price' => 4200,
                'purchase_date' => '2026-08-12',
            ],
        ];

        $data = array_map(fn ($item) => [
            'checklist_id' => $checklistId,
            'product_id' => $products[$item['product']],
            'quantity_planned' => $item['quantity_planned'],
            'unit_id_planned' => $item['unit_planned'] ? $units[$item['unit_planned']] : null,
            'quantity_at_home' => $item['quantity_at_home'],
            'unit_id_at_home' => $item['unit_at_home'] ? $units[$item['unit_at_home']] : null,
            'was_bought' => $item['was_bought'],
            'quantity_bought' => $item['quantity_bought'],
            'unit_id_bought' => $item['unit_bought'] ? $units[$item['unit_bought']] : null,
            'place_id' => $item['place'] ? $places[$item['place']] : null,
            'unit_price' => $item['unit_price'],
            'total_price' => $item['total_price'],
            'purchase_date' => $item['purchase_date'],
            'created_at' => now(),
            'updated_at' => now(),
        ], $items);

        DB::table('checklist_items')->insert($data);
    }
}
