<?php

namespace Database\Seeders;

use App\Models\business\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Catálogo real de productos, extraído de la despensa en producción.
     * Cada fila es [nombre del producto, nombre de la categoría].
     */
    public function run(): void
    {
        $categories = Category::pluck('id', 'name');

        $products = [
            ['Aceite', 'Aceites'],
            ['Aceite oliva', 'Aceites'],
            ['Alcohol', 'Medicamentos'],
            ['Arroz', 'Arroz'],
            ['Arveja desgranada', 'Legumbres'],
            ['Atun', 'Pescado'],
            ['Avena', 'Cereales'],
            ['Azucar', 'Azúcar'],
            ['Bechamel', 'Salsas'],
            ['Boloñesa', 'Salsas'],
            ['Bolsas Orión', 'Limpieza hogar'],
            ['Bombillos', 'Limpieza hogar'],
            ['Cabello de angel', 'Pasta'],
            ['Cafe', 'Café'],
            ['Cebada', 'Cereales'],
            ['Cereal flops', 'Cereales'],
            ['Cereal 500g', 'Cereales'],
            ['Chocolate Tableta', 'Chocolate'],
            ['Chorizo', 'Carnes'],
            ['Color', 'Especias'],
            ['Combo rica', 'Carnes'],
            ['Conchitas', 'Pasta'],
            ['Ducales', 'Galletas'],
            ['Dulces americandy', 'Dulces'],
            ['Estropajo', 'Limpieza hogar'],
            ['Frijol bola roja', 'Legumbres'],
            ['Galletas saltinas', 'Galletas'],
            ['Garbanzo', 'Legumbres'],
            ['Gelatina', 'Dulces'],
            ['Gomas', 'Dulces'],
            ['Gomas orion', 'Dulces'],
            ['Guantes', 'Limpieza hogar'],
            ['Harina arepas', 'Cereales'],
            ['Harina trigo', 'Cereales'],
            ['Huevos', 'Huevos'],
            ['Inhalador', 'Medicamentos'],
            ['Instacream', 'Lácteos'],
            ['Jabón Liquido Manos', 'Jabones'],
            ['Jabón Loza', 'Detergentes'],
            ['Jabón Rey', 'Limpieza hogar'],
            ['Lasagna', 'Pasta'],
            ['Leche', 'Lácteos'],
            ['Lentejas', 'Legumbres'],
            ['Limpion', 'Limpieza hogar'],
            ['Maíz pira', 'Cereales'],
            ['Margarina', 'Lácteos'],
            ['Morcilla', 'Carnes'],
            ['Mortadela', 'Carnes'],
            ['Pan hamburguesa', 'Panadería'],
            ['Pan perro', 'Panadería'],
            ['Pan Sándwich', 'Panadería'],
            ['Panela', 'Azúcar'],
            ['Papel higiénico', 'Papel higiénico'],
            ['Parmesano', 'Lácteos'],
            ['Rallador', 'Limpieza hogar'],
            ['Ramen', 'Pasta'],
            ['Sal', 'Azúcar'],
            ['Salchichas', 'Carnes'],
            ['Salsa Soya', 'Salsas'],
            ['Salsa teriyaki', 'Salsas'],
            ['Saltinas mantequilla', 'Galletas'],
            ['Sándwich', 'Panadería'],
            ['Sardinas', 'Pescado'],
            ['Shampoo', 'Aseo personal'],
            ['Spaguetti', 'Pasta'],
            ['Tallarines', 'Pasta'],
            ['Toalla cocina 660h', 'Limpieza hogar'],
            ['Toallas higiénicas', 'Aseo personal'],
            ['Tostadas', 'Panadería'],
            ['Yogurt', 'Lácteos'],
            ['Alas de pollo', 'Pollo'],
            ['Bola de res', 'Carnes'],
            ['Churrasco', 'Carnes'],
            ['Costilla de cerdo', 'Carnes'],
            ['Costilla de res', 'Carnes'],
            ['Cuadros de res', 'Carnes'],
            ['Carne molida', 'Carnes'],
            ['Carne para asar', 'Carnes'],
            ['Pechuga de pollo', 'Pollo'],
            ['Pollo entero', 'Pollo'],
            ['Pierna pernil', 'Carnes'],
            ['Pierna de cerdo', 'Carnes'],
            ['Sobrebarriga', 'Carnes'],
            ['Tocineta', 'Carnes'],
            ['Lomo visceral', 'Carnes'],
            ['Cadera de res', 'Carnes'],
            ['Frijol cabeza negra', 'Legumbres'],
            ['Frijol caraota', 'Legumbres'],
            ['Papas bbq', 'Snacks'],
            ['Tortilla grande', 'Panadería'],
            ['Agua oxigenada', 'Medicamentos'],
            ['Ajo en Polvo', 'Especias'],
            ['Ambientador', 'Limpieza hogar'],
            ['Baterías AA', 'Limpieza hogar'],
            ['Cabano Snack', 'Snacks'],
            ['Chocolate En Polvo', 'Chocolate'],
            ['Copitos', 'Aseo personal'],
            ['Crema de leche', 'Lácteos'],
            ['Desodorante', 'Aseo personal'],
            ['Doritos fake', 'Snacks'],
            ['Frijol refrito', 'Legumbres'],
            ['Galletas Festival', 'Galletas'],
            ['Galletas chocolate', 'Galletas'],
            ['Galletas club', 'Galletas'],
            ['Helado', 'Lácteos'],
            ['Detergente Líquido', 'Detergentes'],
            ['Jabón Polvo', 'Detergentes'],
            ['Limpiatodo', 'Limpieza hogar'],
            ['Maíz Congelado', 'Legumbres'],
            ['Maní divertido', 'Snacks'],
            ['Mascarilla', 'Aseo personal'],
            ['Mayonesa', 'Salsas'],
            ['Minibrownies', 'Dulces'],
            ['Mostaza', 'Salsas'],
            ['Palitos chocolate', 'Dulces'],
            ['Pan tajado', 'Panadería'],
            ['Papas fósforos', 'Snacks'],
            ['Papas a la francesa', 'Congelados'],
            ['Pasta de tomate', 'Salsas'],
            ['Pastillas baño', 'Limpieza hogar'],
            ['Perlas fragancia', 'Limpieza hogar'],
            ['Pimienta Molida', 'Especias'],
            ['Polvo abrasivo', 'Limpieza hogar'],
            ['Pon quesitos', 'Lácteos'],
            ['Salsa tomate', 'Salsas'],
            ['Suavitel', 'Limpieza hogar'],
            ['Tapabocas', 'Aseo personal'],
            ['Toallas Desinfectante', 'Limpieza hogar'],
            ['Toallas humedas', 'Aseo personal'],
            ['Toallas húmedas mini', 'Aseo personal'],
            ['Toallas mascotas', 'Limpieza hogar'],
            ['Vinagre', 'Salsas'],
            ['Barra de chocolate', 'Chocolate'],
            ['Bocadillo veleño', 'Dulces'],
            ['Yogur griego', 'Lácteos'],
            ['Mogolla', 'Panadería'],
            ['Zanahoria', 'Verduras'],
            ['Plátano', 'Verduras'],
            ['Guatila', 'Verduras'],
            ['Papa Pastusa (Bolsa)', 'Verduras'],
            ['Cebolla cabezona blanca', 'Verduras'],
            ['Tomate', 'Verduras'],
            ['Espinaca', 'Verduras'],
            ['Limón', 'Frutas'],
            ['Raíces chinas', 'Verduras'],
            ['Zuccini', 'Verduras'],
            ['Mandarina', 'Frutas'],
            ['Banano', 'Frutas'],
            ['Arándanos', 'Frutas'],
            ['Agraz', 'Frutas'],
            ['Aguacate', 'Frutas'],
            ['Mora', 'Frutas'],
            ['Papa criolla', 'Verduras'],
            ['Arveja verde', 'Legumbres'],
            ['Lulo', 'Frutas'],
            ['Pimentón', 'Verduras'],
            ['Lechuga', 'Verduras'],
            ['Pepino ensalada', 'Verduras'],
            ['Cebolla cabezona roja', 'Verduras'],
            ['Cebolla larga', 'Verduras'],
            ['Cilantro', 'Verduras'],
            ['Brócoli', 'Verduras'],
            ['Habichuela', 'Verduras'],
            ['Pepino guiso', 'Verduras'],
            ['Panela Don Camilo', 'Azúcar'],
            ['Huevos Don Camilo', 'Huevos'],
            ['Manzana', 'Frutas'],
            ['Papaya', 'Frutas'],
            ['Champiñón', 'Verduras'],
            ['Miel', 'Azúcar'],
            ['Naranja', 'Frutas'],
            ['Cabezas de Ajo', 'Verduras'],
            ['Mazorca', 'Verduras'],
            ['Piña golden', 'Frutas'],
            ['Puerro', 'Verduras'],
            ['Guayaba', 'Frutas'],
            ['Remolacha', 'Verduras'],
            ['Yuca', 'Verduras'],
            ['Café Instantáneo', 'Café'],
            ['Aromáticas', 'Café'],
            ['Mantequilla', 'Lácteos'],
            ['Jamón', 'Carnes'],
            ['Jamón Serrano Tajado', 'Carnes'],
            ['Carne Hamburguesa', 'Carnes'],
            ['Protectores', 'Aseo personal'],
            ['Jabón corporal', 'Jabones'],
            ['Guantes Negros', 'Limpieza hogar'],
            ['Cerveza six', 'Cerveza'],
            ['Arroz con leche', 'Snacks'],
            ['Arepa con queso', 'Panadería'],
            ['Leche Achocolatada', 'Lácteos'],
            ['Avena Bolsa', 'Lácteos'],
            ['Pañuelos Faciales', 'Aseo personal'],
            ['Desengrasante', 'Limpieza hogar'],
            ['Pastillas Tanque', 'Limpieza hogar'],
            ['Pepperoni Tajado', 'Carnes'],
            ['Salami Tajado', 'Carnes'],
            ['Algodón', 'Aseo personal'],
            ['Pan Mini Baguette', 'Panadería'],
            ['Paprika en Polvo', 'Especias'],
            ['Salinas Club', 'Galletas'],
            ['Bom bom bum', 'Dulces'],
            ['Chicharrón Snack', 'Snacks'],
            ['Arveja con cáscara', 'Legumbres'],
            ['Papa Sabanera', 'Verduras'],
        ];

        $data = array_map(fn ($p) => [
            'name' => $p[0],
            'category_id' => $categories[$p[1]],
            'enabled' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ], $products);

        DB::table('products')->insert($data);
    }
}
